### ISSUE TITLE
Event.toString contains dead code

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/Constellation#1]
The `Event.toString()` contains dead code:

        String s = "source: ";
        if (getSource() != null) {
            s += getSource().toString();
        } else {
            s += "none";
        }
        s += "; target: ";
        if (getTarget() != null) {
            s += getTarget().toString();
        } else {
            s += "none";
        }

The  `getSource()` and `getTarget()` calls will never return `null` since the `source` and `target` fields are used to invoke a method in the constructor of `Event`. As a result both `else` clauses are unreachable (also for tests).

**Comment by CerielJacobs** [comment]
Fixed in https://github.com/NLeSC/Constellation/commit/d81c58150e3d5967e02420794b49eac9f7958c0f
