### ISSUE TITLE
Do we need the separation between executor and activity contexts?

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/Constellation#10]
We currently have two types of contexts, `ActivityContext` and `ExecutorContext`. Both have the `UnitContext` and `OrContext` subtypes. 

I'm wondering if we could replace this with a single `Context` implementation (keeping the `Unit` and `Or` subtypes). 

I remember there was a reason for this split, but unfortunately don't remember the reason itself. It probably has to do with the ranges and matching, but I have the feeling there are more elegant solutions for this, like completely hiding the matching in the `impl` package.

**Comment by CerielJacobs** [comment]
Has been resolved in the api-change branch
