### ISSUE TITLE
StealStrategy too complicated

### ISSUE THREAD

**Issue by CerielJacobs** [NLeSC/Constellation#14]
If there are now only two steal strategies left, why do we still need a public constructor? We could just do with the two public possible values. Other values are rejected now anyway.

**Comment by jmaassen** [comment]
Agreed. This is a leftover from changing the API and moving the ranges into the context. 

I've replace the public constructor with a private one. I guess the `getStrategy` should also be removed ?  It returns the byte opcode, which does not make sense anymore.

**Comment by jmaassen** [comment]
done
