### ISSUE TITLE
API seperation seems confused

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/Constellation#2]
The API seperation of Constellation seems confused. For example, the top level API contains an `ibis.constellation.ActivityIdentifier` class that  extends an `ibis.constellation.impl.ActivityIdentifierImpl` class in the implementation subpackage. This does not make sense?

Either the top level should truely be a separate API (and therefore not import things from the implementation), or the whole thing should be flattened ?

**Comment by jmaassen** [comment]
The same goes for `Activity` and `ActivityBase`

**Comment by jmaassen** [comment]
Interestingly, the `ActivityBase`, `ActivityIdentifierImpl`, and `ExecutorBase` do not depend on anything else in the implementation subpackage and they are abstract classes. Why are these not in the top level API?

**Comment by CerielJacobs** [comment]
All resolved in api-change branch
