### ISSUE TITLE
OrActivityContext accepts null values

### ISSUE THREAD

**Issue by jmaassen** [NLeSC/Constellation#7]
The `OrActivityContext` gets an array of `UnitActivityContext` as first parameter, but does not check in the constructor whether or not one of the array values is `null`. For example: 

       new OrActivityContext(new UnitActivityContext[2], true)

is accepted without complaints. However, not all method can handle these null values. For example, `hashcode` can but `equals` cannot, and neither can the constructor with `false` as the last parameter instead of `true`. 

This suggest the the null values should not be accepted in the first place. Alternatively, the array should be collapsed to not contain any `null` values anymore (as it is copied anyway).

Will fix this in the unittest branch.

**Comment by CerielJacobs** [comment]
Likewise for OrExecutorContexts.

**Comment by jmaassen** [comment]
OK, will fix

**Comment by jmaassen** [comment]
Fixed in 55b1445228cc9c66d649d0cc5e1335247a653d1e
